In [1]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier 
from sklearn import metrics
  
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import warnings
import sys
import os 
DeprecationWarning('ignore')
warnings.filterwarnings('ignore', message='Ignore mar')

In [2]:
os.getcwd()

'C:\\Users\\Shruti'

In [3]:
df=pd.read_csv('Traffic accident data chp 5.csv')

In [4]:
len(df.columns)

38

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2294 entries, 0 to 2293
Data columns (total 38 columns):
Country                      2203 non-null object
State                        2203 non-null object
month                        2203 non-null object
Date                         2203 non-null object
day                          2203 non-null object
time                         2203 non-null float64
harmful-event                2203 non-null object
manner-of-collision          2203 non-null object
person-type                  2203 non-null object
seating-position             2203 non-null object
age                          2203 non-null object
age-range                    2203 non-null float64
gender                       2203 non-null object
race                         2203 non-null object
injury-severity              2203 non-null object
air-bag                      2203 non-null object
transported-for-treatment    2203 non-null object
protection-system            2203 non-nul

In [6]:
df.head()

Country          State month        Date  day    time harmful-event  \
0   India  Muzaffarnagar   Jan  01-01-2016  Mon   815.0       Harmful   
1   India  Muzaffarnagar   Jan  02-01-2016  Mon  1330.0       Harmful   
2   India  Muzaffarnagar   Jan  03-01-2016  Mon   805.0       Harmful   
3   India  Muzaffarnagar   Jan  04-01-2016  Mon   805.0       Harmful   
4   India  Muzaffarnagar   Jan  05-01-2016  Mon  1705.0       Harmful   

  manner-of-collision person-type seating-position  ... road-type  \
0  Collision occurred      Driver        Back-side  ...   Highway   
1  Collision occurred      Driver        Back-side  ...     Local   
2  Collision occurred      Driver        Back-side  ...   Highway   
3  Collision occurred      Driver        Back-side  ...   Highway   
4  Collision occurred      Driver        Back-side  ...   Highway   

   n0-of-lanes sorrounding-area road-features light-condion  \
0        Three      Agriculture         Curve     Day light   
1        Three      Residential         Curve     Day light   
2          Two      Residential         Curve      No light   
3          Two      Residential      Straight    Road light   
4          Two      Residential      Straight      No light   

           weather-conditions following-traffic-rules type-of-vehicle  \
0                       Other            Not-Followed             Car   
1     Fine without high winds            Not-Followed             Bus   
2     Fine without high winds            Not-Followed             Car   
3     Fine without high winds                Followed             Car   
4  Raining without high winds            Not-Followed             Car   

  causality-class Severity Class  
0      Pedestrian          Minor  
1          Driver          Minor  
2          Driver          Minor  
3          Driver          Minor  
4          Driver          Minor  

[5 rows x 38 columns]

In [7]:
def null_percent(df):
    for column in df.columns:
        percent=df[column].isnull().sum()/df[column].shape[0]
        print(column, '=', (percent.round(3))*100)

In [8]:
null_percent(df)

Country = 4.0
State = 4.0
month = 4.0
Date = 4.0
day = 4.0
time = 4.0
harmful-event = 4.0
manner-of-collision = 4.0
person-type = 4.0
seating-position = 4.0
age = 4.0
age-range = 4.0
gender = 4.0
race = 4.0
injury-severity = 4.0
air-bag = 4.0
transported-for-treatment = 4.0
protection-system = 4.0
ejection = 4.0
extrication = 4.0
dead-on-arrival = 4.0
year-of-death = 4.0
month-of-death = 76.6
time-of-death = 86.4
alcohol-test = 4.0
alcohol-test-method = 78.60000000000001
drug-test = 4.0
drug-involvement = 75.7
road-type = 4.0
n0-of-lanes = 4.0
sorrounding-area = 4.0
road-features = 4.0
light-condion = 4.0
weather-conditions = 4.0
following-traffic-rules = 4.0
type-of-vehicle = 4.0
causality-class = 4.0
Severity Class = 4.0


In [9]:
df.isnull().sum()

Country                        91
State                          91
month                          91
Date                           91
day                            91
time                           91
harmful-event                  91
manner-of-collision            91
person-type                    91
seating-position               91
age                            91
age-range                      91
gender                         91
race                           91
injury-severity                91
air-bag                        91
transported-for-treatment      91
protection-system              91
ejection                       91
extrication                    91
dead-on-arrival                91
year-of-death                  91
month-of-death               1757
time-of-death                1982
alcohol-test                   91
alcohol-test-method          1802
drug-test                      91
drug-involvement             1737
road-type                      91
n0-of-lanes   

In [10]:
df["State"].value_counts()

Muzaffarnagar     805
Andhra Pradesh    672
Uttar Pradesh     519
Maharashtra       207
Name: State, dtype: int64

In [11]:
df.drop('Country', axis=1, inplace=True)
df.drop('drug-involvement', axis=1, inplace=True)
df.drop('alcohol-test-method', axis=1, inplace=True)
df.drop('time-of-death', axis=1, inplace=True)
df.drop('month-of-death', axis=1, inplace=True)
df.drop('Date', axis=1, inplace=True)

In [12]:
for i in range(32):
    print(df[df.columns[i]].value_counts())

Muzaffarnagar     805
Andhra Pradesh    672
Uttar Pradesh     519
Maharashtra       207
Name: State, dtype: int64
Dec     260
Apr     203
Feb     202
Jan     202
Mar     202
Aug     181
Nov     180
Jun     160
Oct     160
May     159
Sept    157
Jul     137
Name: month, dtype: int64
Mon     620
Fri     540
Sun     363
Sat     330
Thur    140
Tues    110
Wed     100
Name: day, dtype: int64
1700.0    34
1600.0    29
1800.0    29
1900.0    22
1630.0    21
          ..
1749.0     1
906.0      1
1721.0     1
1706.0     1
1031.0     1
Name: time, Length: 633, dtype: int64
Normal     1517
Harmful     686
Name: harmful-event, dtype: int64
Non-collision         1816
Collision occurred     387
Name: manner-of-collision, dtype: int64
Passenger    1941
Driver        262
Name: person-type, dtype: int64
Back-side     1905
Front-side     298
Name: seating-position, dtype: int64
young    2003
old       200
Name: age, dtype: int64
24.0    68
23.0    67
26.0    66
20.0    66
18.0    65
        ..
96.0  

In [13]:
df.head()

State month  day    time harmful-event manner-of-collision  \
0  Muzaffarnagar   Jan  Mon   815.0       Harmful  Collision occurred   
1  Muzaffarnagar   Jan  Mon  1330.0       Harmful  Collision occurred   
2  Muzaffarnagar   Jan  Mon   805.0       Harmful  Collision occurred   
3  Muzaffarnagar   Jan  Mon   805.0       Harmful  Collision occurred   
4  Muzaffarnagar   Jan  Mon  1705.0       Harmful  Collision occurred   

  person-type seating-position   age  age-range  ... road-type n0-of-lanes  \
0      Driver        Back-side  old        61.0  ...   Highway       Three   
1      Driver        Back-side  old        36.0  ...     Local       Three   
2      Driver        Back-side  old        32.0  ...   Highway         Two   
3      Driver        Back-side  old        30.0  ...   Highway         Two   
4      Driver        Back-side  old        26.0  ...   Highway         Two   

  sorrounding-area road-features light-condion          weather-conditions  \
0      Agriculture         Curve     Day light                       Other   
1      Residential         Curve     Day light     Fine without high winds   
2      Residential         Curve      No light     Fine without high winds   
3      Residential      Straight    Road light     Fine without high winds   
4      Residential      Straight      No light  Raining without high winds   

  following-traffic-rules type-of-vehicle causality-class  Severity Class  
0            Not-Followed             Car      Pedestrian           Minor  
1            Not-Followed             Bus          Driver           Minor  
2            Not-Followed             Car          Driver           Minor  
3                Followed             Car          Driver           Minor  
4            Not-Followed             Car          Driver           Minor  

[5 rows x 32 columns]

In [14]:
df.State.value_counts()

Muzaffarnagar     805
Andhra Pradesh    672
Uttar Pradesh     519
Maharashtra       207
Name: State, dtype: int64

In [15]:
df=df.dropna()

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2203 entries, 0 to 2202
Data columns (total 32 columns):
State                        2203 non-null object
month                        2203 non-null object
day                          2203 non-null object
time                         2203 non-null float64
harmful-event                2203 non-null object
manner-of-collision          2203 non-null object
person-type                  2203 non-null object
seating-position             2203 non-null object
age                          2203 non-null object
age-range                    2203 non-null float64
gender                       2203 non-null object
race                         2203 non-null object
injury-severity              2203 non-null object
air-bag                      2203 non-null object
transported-for-treatment    2203 non-null object
protection-system            2203 non-null object
ejection                     2203 non-null object
extrication                  2203 non-nul

In [17]:
for i in range(32): 
    print(df[df.columns[i]].value_counts())

Muzaffarnagar     805
Andhra Pradesh    672
Uttar Pradesh     519
Maharashtra       207
Name: State, dtype: int64
Dec     260
Apr     203
Feb     202
Jan     202
Mar     202
Aug     181
Nov     180
Jun     160
Oct     160
May     159
Sept    157
Jul     137
Name: month, dtype: int64
Mon     620
Fri     540
Sun     363
Sat     330
Thur    140
Tues    110
Wed     100
Name: day, dtype: int64
1700.0    34
1600.0    29
1800.0    29
1900.0    22
1630.0    21
          ..
1749.0     1
906.0      1
1721.0     1
1706.0     1
1031.0     1
Name: time, Length: 633, dtype: int64
Normal     1517
Harmful     686
Name: harmful-event, dtype: int64
Non-collision         1816
Collision occurred     387
Name: manner-of-collision, dtype: int64
Passenger    1941
Driver        262
Name: person-type, dtype: int64
Back-side     1905
Front-side     298
Name: seating-position, dtype: int64
young    2003
old       200
Name: age, dtype: int64
24.0    68
23.0    67
26.0    66
20.0    66
18.0    65
        ..
96.0  

In [18]:
df2=df

In [19]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
df['State'] = labelencoder.fit_transform(df['State'])
df['month'] = labelencoder.fit_transform(df['month'])
df['day'] = labelencoder.fit_transform(df['day'])
df['harmful-event'] = labelencoder.fit_transform(df['harmful-event'])
df['manner-of-collision'] = labelencoder.fit_transform(df['manner-of-collision'])
df['person-type'] = labelencoder.fit_transform(df['person-type'])
df['seating-position'] = labelencoder.fit_transform(df['seating-position'])
df['age'] = labelencoder.fit_transform(df['age'])
df['gender'] = labelencoder.fit_transform(df['gender'])
df['race'] = labelencoder.fit_transform(df['race'])
df['injury-severity'] = labelencoder.fit_transform(df['injury-severity'])
df['air-bag'] = labelencoder.fit_transform(df['air-bag'])
df['transported-for-treatment'] = labelencoder.fit_transform(df['transported-for-treatment'])
df['protection-system'] = labelencoder.fit_transform(df['protection-system'])
df['ejection'] = labelencoder.fit_transform(df['ejection'])
df['extrication'] = labelencoder.fit_transform(df['extrication'])
df['alcohol-test'] = labelencoder.fit_transform(df['alcohol-test'])
df['drug-test'] = labelencoder.fit_transform(df['drug-test'])
df['road-type'] = labelencoder.fit_transform(df['road-type'])
df['n0-of-lanes'] = labelencoder.fit_transform(df['n0-of-lanes'])
df['sorrounding-area'] = labelencoder.fit_transform(df['sorrounding-area'])
df['road-features'] = labelencoder.fit_transform(df['road-features'])
df['light-condion'] = labelencoder.fit_transform(df['light-condion'])
df['weather-conditions'] = labelencoder.fit_transform(df['weather-conditions'])
df['following-traffic-rules'] = labelencoder.fit_transform(df['following-traffic-rules'])
df['type-of-vehicle'] = labelencoder.fit_transform(df['type-of-vehicle'])
df['causality-class'] = labelencoder.fit_transform(df['causality-class'])
df['Severity Class'] = labelencoder.fit_transform(df['Severity Class'])
df['dead-on-arrival'] = labelencoder.fit_transform(df['dead-on-arrival'])

In [20]:
df

State  month  day    time  harmful-event  manner-of-collision  \
0         2      4    1   815.0              0                    0   
1         2      4    1  1330.0              0                    0   
2         2      4    1   805.0              0                    0   
3         2      4    1   805.0              0                    0   
4         2      4    1  1705.0              0                    0   
...     ...    ...  ...     ...            ...                  ...   
2198      1      2    3  1515.0              1                    1   
2199      1      2    3  1935.0              1                    1   
2200      1      2    3  2111.0              1                    1   
2201      1      2    3  2320.0              1                    1   
2202      1      2    3  1400.0              1                    1   

      person-type  seating-position  age  age-range  ...  road-type  \
0               0                 0    0       61.0  ...          0   
1               0                 0    0       36.0  ...          1   
2               0                 0    0       32.0  ...          0   
3               0                 0    0       30.0  ...          0   
4               0                 0    0       26.0  ...          0   
...           ...               ...  ...        ...  ...        ...   
2198            1                 0    1       21.0  ...          0   
2199            1                 0    1       23.0  ...          0   
2200            1                 0    1       20.0  ...          0   
2201            1                 0    1       34.0  ...          0   
2202            1                 0    1       27.0  ...          0   

      n0-of-lanes  sorrounding-area  road-features  light-condion  \
0               1                 0              0              0   
1               1                 3              0              0   
2               2                 3              0              1   
3               2                 3              2              2   
4               2                 3              2              1   
...           ...               ...            ...            ...   
2198            0                 3              0              0   
2199            0                 3              0              0   
2200            0                 3              0              0   
2201            0                 3              0              0   
2202            1                 3              0              0   

      weather-conditions  following-traffic-rules  type-of-vehicle  \
0                      3                        1                2   
1                      1                        1                1   
2                      1                        1                2   
3                      1                        0                2   
4                      5                        1                2   
...                  ...                      ...              ...   
2198                   7                        1                2   
2199                   5                        1                0   
2200                   5                        1                2   
2201                   1                        1                0   
2202                   5                        1                2   

      causality-class  Severity Class  
0                   1               2  
1                   0               2  
2                   0               2  
3                   0               2  
4                   0               2  
...               ...             ...  
2198                1               2  
2199                1               2  
2200                1               2  
2201                1               2  
2202                1               2  

[2203 rows x 32 columns]

In [21]:
df1=df

In [22]:
Y=df1[['Severity Class','causality-class','injury-severity','harmful-event']]
X=df1.drop(['Severity Class','causality-class','injury-severity','harmful-event'],axis=True)
y=df1[['Severity Class','causality-class','injury-severity','harmful-event']].values
x=df1.drop(['Severity Class','causality-class','injury-severity','harmful-event'],axis=True).values

In [23]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2203 entries, 0 to 2202
Data columns (total 28 columns):
State                        2203 non-null int32
month                        2203 non-null int32
day                          2203 non-null int32
time                         2203 non-null float64
manner-of-collision          2203 non-null int32
person-type                  2203 non-null int32
seating-position             2203 non-null int32
age                          2203 non-null int32
age-range                    2203 non-null float64
gender                       2203 non-null int32
race                         2203 non-null int32
air-bag                      2203 non-null int32
transported-for-treatment    2203 non-null int32
protection-system            2203 non-null int32
ejection                     2203 non-null int32
extrication                  2203 non-null int32
dead-on-arrival              2203 non-null int32
year-of-death                2203 non-null float64
alcoh

In [24]:
Y.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2203 entries, 0 to 2202
Data columns (total 4 columns):
Severity Class     2203 non-null int32
causality-class    2203 non-null int32
injury-severity    2203 non-null int32
harmful-event      2203 non-null int32
dtypes: int32(4)
memory usage: 51.6 KB


In [25]:
df.to_csv('Traffic_clean.csv')

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(x,y,test_size = 0.25, random_state=43)

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) 

In [28]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3, p=1, metric='minkowski', n_jobs=-1, weights='distance')
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=3, p=1,
                     weights='distance')

In [29]:
y_pred = classifier.predict(X_test)

In [30]:
print("\n---------------------------\n")
print("Predicted Values for Test Set :\n",y_pred)
print("\n---------------------------\n")
print("Actual Values for Test Set :\n",y_test)


---------------------------

Predicted Values for Test Set :
 [[2 0 0 0]
 [2 1 0 0]
 [2 1 1 1]
 ...
 [2 1 0 0]
 [2 1 0 1]
 [1 0 1 1]]

---------------------------

Actual Values for Test Set :
 [[2 0 0 0]
 [2 1 0 0]
 [2 1 1 1]
 ...
 [2 1 0 0]
 [2 0 0 1]
 [1 0 1 1]]


In [31]:
1-np.sum(np.not_equal(y_test, y_pred))/float(y_test.size)

0.9001814882032668

In [32]:
X_train, X_test, y_train,y_test = train_test_split(x,y,test_size = 0.25, random_state=43)
X_train1, X_test1, y_train1,y_test1 =np.array(X_train), np.array(X_test), np.array(y_train),np.array(y_test)
X_train1 = sc.fit_transform(X_train1)
X_test1 = sc.transform(X_test1) 
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
y_train1 = mlb.fit_transform(y_train1)

In [33]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
clf = OneVsRestClassifier(SVC())
clf.fit(X_train1,y_train1)

OneVsRestClassifier(estimator=SVC(C=1.0, cache_size=200, class_weight=None,
                                  coef0=0.0, decision_function_shape='ovr',
                                  degree=3, gamma='auto_deprecated',
                                  kernel='rbf', max_iter=-1, probability=False,
                                  random_state=None, shrinking=True, tol=0.001,
                                  verbose=False),
                    n_jobs=None)

In [34]:
y_pred1 = clf.predict(X_test1)
y_test1 = mlb.fit_transform(y_test1)
1-np.sum(np.not_equal(y_test1, y_pred1))/float(y_test1.size)

0.8868723532970357

In [35]:
X_train, X_test, y_train,y_test = train_test_split(x,y,test_size = 0.25, random_state=43)
X_train2, X_test2, y_train2,y_test2 =np.array(X_train), np.array(X_test), np.array(y_train),np.array(y_test)
X_train2 = sc.fit_transform(X_train2)
X_test2 = sc.transform(X_test2) 
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
print(y_train2.shape)
y_train2 = mlb.fit_transform(y_train2)
y_test2 = mlb.fit_transform(y_test2)
print(y_train2.shape)

(1652, 4)
(1652, 3)


In [36]:
log = OneVsRestClassifier(LogisticRegression(random_state=12,solver="liblinear"))
log.fit(X_train2,y_train2)

OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=12,
                                                 solver='liblinear', tol=0.0001,
                                                 verbose=0, warm_start=False),
                    n_jobs=None)

In [37]:
y_pred2 = log.predict(X_test2)
1-np.sum(np.not_equal(y_test2, y_pred2))/float(y_test2.size)


0.8596491228070176

In [38]:
X_train, X_test, y_train,y_test = train_test_split(x,y,test_size = 0.25, random_state=43)
X_train3, X_test3, y_train3,y_test3 =np.array(X_train), np.array(X_test), np.array(y_train),np.array(y_test) 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) 
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
y_train3 = mlb.fit_transform(y_train3)
y_test3 = mlb.fit_transform(y_test3)
from sklearn.naive_bayes import BernoulliNB
nb = OneVsRestClassifier(BernoulliNB())
nb.fit(X_train3,y_train3)

OneVsRestClassifier(estimator=BernoulliNB(alpha=1.0, binarize=0.0,
                                          class_prior=None, fit_prior=True),
                    n_jobs=None)

In [39]:
y_pred3 = nb.predict(X_test3)
1-np.sum(np.not_equal(y_test3, y_pred3))/float(y_test3.size)

0.8408953418027828

In [40]:
X_train4, X_test4, y_train4,y_test4 =np.array(X_train), np.array(X_test), np.array(y_train),np.array(y_test) 

from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
y_train4 = mlb.fit_transform(y_train4)
y_test4 = mlb.fit_transform(y_test4)
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(X_train4,y_train4)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [41]:
y_pred4 = tree.predict(X_test4)
1-np.sum(np.not_equal(y_test4, y_pred4))/float(y_test4.size)

0.9056261343012704

In [42]:
X_train5, X_test5, y_train5,y_test5 =np.array(X_train), np.array(X_test), np.array(y_train),np.array(y_test) 
from sklearn.preprocessing import MultiLabelBinarizer
X_train5 = sc.fit_transform(X_train5)
X_test5 = sc.transform(X_test5) 
mlb = MultiLabelBinarizer()
y_train5 = mlb.fit_transform(y_train5)
y_test5 = mlb.fit_transform(y_test5)
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier()
forest.fit(X_train5,y_train5)

D:\ANACONDA\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [43]:
y_pred5 = forest.predict(X_test5)
1-np.sum(np.not_equal(y_test5, y_pred5))/float(y_test5.size)

0.9026013309134906

In [44]:
y_pred = classifier.predict(X_test)
#KNN = round(classifier.score(X_test, y_test), 2) 
  
mae_knn = metrics.mean_absolute_error(y_test, y_pred) 
mse_knn = metrics.mean_squared_error(y_test, y_pred) 
acc_knn=1-np.sum(np.not_equal(y_test, y_pred))/float(y_test.size)
rmse_knn=np.sqrt(np.mean((y_test-y_pred)**2))

compare_models = pd.DataFrame( 
    {  'Model' : ['KNN'], 
       #'Score' : [KNN], 
        'MAE'  : [mae_knn], 
        'MSE'  : [mse_knn],
     'accuracy' : [acc_knn],
     'rmse' : [rmse_knn]
    }) 
  
print(compare_models) 
  

  Model       MAE       MSE  accuracy      rmse
0   KNN  0.107078  0.121597  0.900181  0.348708


In [45]:

  
y_pred2 = log.predict(X_test2)
LogReg = round(log.score(X_test2, y_test2),2) 
  
mae_lr = round(metrics.mean_absolute_error(y_test2, y_pred2), 4) 
mse_lr = round(metrics.mean_squared_error(y_test2, y_pred2), 4) 
acc_lr=1-np.sum(np.not_equal(y_test2, y_pred2))/float(y_test2.size)
rmse_lr=np.sqrt(np.mean((y_test2-y_pred2)**2))

y_pred3 = nb.predict(X_test3)
NB = round(nb.score(X_test3, y_test3), 2) 
  
mae_nb = metrics.mean_absolute_error(y_test3, y_pred3) 
mse_nb = metrics.mean_squared_error(y_test3, y_pred3)
acc_nb=1-np.sum(np.not_equal(y_test3, y_pred3))/float(y_test3.size)
rmse_nb=np.sqrt(np.mean((y_test3-y_pred3)**2))

y_pred4 = tree.predict(X_test4)
DT= round(tree.score(X_test4, y_test4), 2) 
mae_dt = metrics.mean_absolute_error(y_test4, y_pred4) 
mse_dt = metrics.mean_squared_error(y_test4, y_pred4) 
acc_dt=1-np.sum(np.not_equal(y_test4, y_pred4))/float(y_test4.size)
rmse_dt=np.sqrt(np.mean((y_test4-y_pred4)**2))  

y_pred5 = forest.predict(X_test5)
RF= round(forest.score(X_test5, y_test5), 2) 
mae_rf = metrics.mean_absolute_error(y_test5, y_pred5) 
mse_rf = metrics.mean_squared_error(y_test5, y_pred5)   
acc_rf=1-np.sum(np.not_equal(y_test5, y_pred5))/float(y_test5.size)
rmse_rf=np.sqrt(np.mean((y_test5-y_pred5)**2))

y_pred1 = clf.predict(X_test1)
#y_test1 = mlb.fit_transform(y_test1)
SVM = round(clf.score(X_test1, y_test1), 2) 
  
mae_svm = metrics.mean_absolute_error(y_test1, y_pred1) 
mse_svm = metrics.mean_squared_error(y_test1, y_pred1)
acc_svm=1-np.sum(np.not_equal(y_test1, y_pred1))/float(y_test1.size)
rmse_svm=np.sqrt(np.mean((y_test1-y_pred1)**2))
  

compare_models = pd.DataFrame( 
    {  'Model' : ['LogReg', 'NB','DT','RF','SVM'], 
       'Score' : [LogReg, NB, DT,RF,SVM], 
        'MAE'  : [mae_lr, mae_nb,mae_dt,mae_rf,mae_svm], 
        'MSE'  : [mse_lr, mse_nb,mse_dt,mse_rf,mse_svm],
        'Accuracy'  : [acc_lr, acc_nb,acc_dt,acc_rf,acc_svm],
        'RMSE' : [rmse_lr,rmse_nb,rmse_dt,rmse_rf,rmse_svm]
    }) 
  
print(compare_models) 
  

    Model  Score       MAE       MSE  Accuracy      RMSE
0  LogReg   0.60  0.140400  0.140400  0.859649  0.374634
1      NB   0.57  0.159105  0.159105  0.840895  0.398879
2      DT   0.74  0.094374  0.094374  0.905626  0.307203
3      RF   0.72  0.097399  0.097399  0.902601  0.312088
4     SVM   0.67  0.113128  0.113128  0.886872  0.336345


In [46]:
from sklearn.metrics import precision_recall_fscore_support

In [47]:
precision_recall_fscore_support(y_test1, y_pred1, average='macro')

(0.8919410893838489, 0.9881194287801134, 0.9367366650838173, None)

In [48]:
precision_recall_fscore_support(y_test2, y_pred2, average='macro')

(0.8731881516631037, 0.9798702598373028, 0.9222906202115208, None)

In [49]:
precision_recall_fscore_support(y_test3, y_pred3, average='macro')

(0.8808518011855906, 0.9443482554467787, 0.9100872710385236, None)

In [50]:
precision_recall_fscore_support(y_test4, y_pred4, average='macro')

(0.9463760862556327, 0.9399889901299585, 0.9430862616824763, None)

In [51]:
precision_recall_fscore_support(y_test5, y_pred5, average='macro')

(0.9344248250504137, 0.9516375181449784, 0.9426755242088962, None)